[project]
name = "amphimixis"
version = "0.1.0"
description = "Build automation and profiling tool for Linux projects across varios architectures."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "paramiko>=4.0.0",
]

[dependency-groups]
dev = [
    "black>=25.9.0",
    "mypy>=1.18.2",
    "pylint>=3.3.8",
]
